In [1]:
from sklearn.datasets import load_iris
from synthcity.plugins import Plugins
from synthcity.metrics import evaluate
import warnings
warnings.filterwarnings('ignore')

X, y = load_iris(return_X_y=True, as_frame=True)
X["target"] = y        

X

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
generator = Plugins().get("dummy_sampler")
generator.fit(X, y)

X_gen = generator.generate(1000)

print("Dummy resampler")
evaluate(
    X.drop(columns=["target"]),
    X["target"],
    X_gen.drop(columns=["target"]),
    X_gen["target"],
)

Dummy resampler

In [ ]:
generator = Plugins().get("random_noise")
generator.fit(X, y)

X_gen = generator.generate(1000)

print("Random noise")
evaluate(
    X.drop(columns=["target"]),
    X["target"],
    X_gen.drop(columns=["target"]),
    X_gen["target"],
)